eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

#Setting the logging levels for the service
logging:
    level:
        com.netflix: INFO
        org.springframework.web: INFO
        com.thoughtmechanix: INFO
        com.example.licenseservice: DEBUG

server:
    error:
        include-exception: true

